### PR TITLE
fix: email formatting

### PR DESCRIPTION
**Pull request by rooterkyberian**

### CODE REVIEW

**Comment by henryiii** [comment]
This also removes names if they don't have an email attached, while the original code puts the name in with empty email.

**Comment by henryiii** [comment]
Looking at https://packaging.python.org/en/latest/specifications/pyproject-toml/#authors-maintainers, I think the new behavior is likely correct, though I think it might not handle missing name correctly still.

**Review by henryiii — APPROVED** [review]

**Comment by rooterkyberian** [comment]
@henryiii anything I can help with to get it merged?

**Comment by henryiii** [comment]
I'm waiting on pre-commit to be reactivated (https://github.com/pypa/python-pyproject-metadata/issues/90) then will merge this.

**Pull request merged**
